### ISSUE TITLE
Unhandled KeyError 

### ISSUE THREAD

**Issue by richardbrodie** [antegs/syncseen#1]
I am trying to sync between two instances of jellyfin running on the same machine. They have two identical libraries set up each, "TV" located locally at `/tv` and "Films" at `/films`.

I run with the command `python3 syncseen.py -shost=http://localhost:8096 -dhost=http://localhost:8097 -skey=12345 -dkey=abcde -u richard`

I get the following error:
```
--- Processing Source
richard 0
Paths not corrected.
Traceback (most recent call last):
  File "syncseen.py", line 190, in <module>
    loadedusers = process("Source", args.shost, args.skey)
  File "syncseen.py", line 138, in process
    if itemdb['MediaSources'][0]['Type'] == "Default":
KeyError: 'MediaSources'
```

I tried editing the relevant line in the script to be `if 'MediaSources' in itemdb.keys() and itemdb['MediaSources'][0]['Type'] == "Default":` and it runs without throwing an exception. However a lot of "Paths not corrected." is output, and eventually a lot of "Item not in source:"

Source jellyfin is 10.5.5 and destination is 10.6.0 nightly.

**Comment by antegs** [comment]
Haven't tested the new API in 10.6.0 so it might not work there.  Does the following, when run on 10.5.5, create a file without an error? If yes, the new API is the problem.
```
python3 syncseen.py -shost=http://localhost:8096 -skey=12345 -u richard -t episode -o file.txt
```

**Comment by richardbrodie** [comment]
It does produce a file, but it only contains about 7 items. That's several orders of magnitude fewer than expected.
```
{
  'richard:Aliens (1986)/Aliens (1986) - Remux-1080p.AVC.DTS-HD.MA.[EN+Chinese].mkv': False,
  ...etc
}
```

**Comment by antegs** [comment]
Looks like there is something wrong with your setup.  When using the "-t episode" option it should only return episodes of tv series but it looks like yours returns movies?

Can you try to get some stats?
```
python3 syncseen.py -shost=http://localhost:8096 -skey=12345 -u richard --stats
```

**Comment by richardbrodie** [comment]
Ah oops, I missed the `-t episode` flag. With that it just produces a file containing `{}`.

the `--stats` flag seems to work as intended though. 
```
--- Source stats:
Users: 1
Total Movies: 287
Total Episodes: 9545
Total Videos: 9
richard:Episode:NotPlayed: 7115
richard:Episode:Played: 2430
richard:Movie:NotPlayed: 242
richard:Movie:Played: 45
richard:Video:NotPlayed: 9
```
I'd guess those 9 `Video`s are the ones that made it into the first output file.

**Comment by antegs** [comment]
That is promising.  I put up a debug script at https://pastebin.com/k7Lrnxw4
It should show a list of paths on the server and a single episode object.
Can you run it like below and post your result in pastebin?
```
python3 syncseen-d1.py -shost=http://localhost:8096 -skey=12345 -u richard -t episode
```

**Comment by richardbrodie** [comment]
https://pastebin.com/LgukTwuH

**Comment by antegs** [comment]
Thanks. Here is a temporary solution but you should be able to generate an output file with this. Add this line:
```
import re; itempath = re.sub("^smb://.*?/", "/", itempath)
```
right above this line:
```
itempathbefore = itempath
```
Then run like before:
```
python3 syncseen.py -shost=http://localhost:8096 -skey=12345 -u richard -t episode -o file.txt
```

**Comment by richardbrodie** [comment]
Perfect, that seems to fix it.

**Comment by antegs** [comment]
Good to hear.  If you want to try making it work on the 10.6.0 API, too, open a new issue and we can take it from there.

**Comment by richardbrodie** [comment]
I don't think the API has changed much in 10.6.0, since I was able to successfully sync films and episodes to the new instance.

**Comment by antegs** [comment]
Thanks for letting me know.
